import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PRAISE DASHBOARD",
  description: "Generated by create next app",
    icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
  taskinput,
  navbar,
}: Readonly<{
  children: React.ReactNode,
  taskinput: React.ReactNode,
   navbar: React.ReactNode,
}>) {
  return (
       <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-white`}
      >
        <header className="font-bold flex z-100 justify-between bg-black p-7 fixed top-0 left-0 right-0 text-white">{navbar}</header>
        <main className="pt-20 z-50 justify-center items-center h-screen absolute overflow-y-auto">{children}</main>
        <aside className="justify-center items-center flex flex-col absolute bottom-0 right-0 top-20 left-250 border-l-2 border-black">{taskinput}</aside>
      </body>   
       </html>   
  );
}
